CREATE DATABASE IF NOT EXISTS VMServerDB;

USE VMServerDB;

CREATE TABLE IF NOT EXISTS Image(ImageID INTEGER PRIMARY KEY, 
	osImagePath VARCHAR(100), dataImagePath VARCHAR(100),
	definitionFilePath VARCHAR(100), bootable BOOL);
	
CREATE TABLE IF NOT EXISTS ActiveVM(domainName VARCHAR(30) PRIMARY KEY, ImageID INTEGER, 
	VNCPort INTEGER, VNCPass VARCHAR(65),
	userId INTEGER, websockifyPID INTEGER,
	osImagePath VARCHAR(100), dataImagePath VARCHAR(100),
	macAddress VARCHAR(20), uuid VARCHAR(40));

CREATE TABLE IF NOT EXISTS ActiveDomainUIDs(domainName VARCHAR(30) PRIMARY KEY, commandID VARCHAR(70) NOT NULL,
	FOREIGN KEY (domainName) REFERENCES ActiveVM(domainName) ON DELETE CASCADE ON UPDATE CASCADE);
	
CREATE TABLE IF NOT EXISTS CompressionQueue(position INTEGER AUTO_INCREMENT PRIMARY KEY, data VARCHAR(420));
						
CREATE TABLE IF NOT EXISTS TransferQueue(position INTEGER AUTO_INCREMENT PRIMARY KEY, data VARCHAR(230));
						
CREATE TABLE IF NOT EXISTS ConnectionDataDictionary(dict_key VARCHAR(70) PRIMARY KEY, value VARCHAR(21));
