'''
Created on Jun 2, 2013

@author: luis
'''

from ccutils.enums import enum

COMMAND_OUTPUT_TYPE = enum("VM_SERVER_REGISTRATION_ERROR", "VM_SERVER_BOOTUP_ERROR", 
                           "VM_CONNECTION_DATA", "VM_BOOT_FAILURE", "VM_SERVER_UNREGISTRATION_ERROR",
                           "VM_SERVER_SHUTDOWN_ERROR", "DOMAIN_DESTRUCTION_ERROR", "DOMAIN_REBOOT_ERROR",  
                           "VM_SERVER_CONFIGURATION_CHANGE_ERROR", "CONNECTION_ERROR", "COMMAND_TIMED_OUT", 
                           "IMAGE_DEPLOYMENT_ERROR", "DELETE_IMAGE_FROM_SERVER_ERROR", "IMAGE_CREATION_ERROR", 
                           "IMAGE_EDITION_ERROR", "DELETE_IMAGE_FROM_INFRASTRUCTURE_ERROR",
                           "AUTO_DEPLOY_ERROR", "VM_SERVER_INTERNAL_ERROR", "IMAGE_DEPLOYED", "IMAGE_CREATED", 
                           "IMAGE_EDITED", "IMAGE_DELETED")